config/routes.rb
Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'

  get 'settings', to: 'settings#index'
  patch 'settings', to: 'settings#update'
  get 'gender', to: 'settings#gender'
  patch 'gender', to: 'settings#set_gender'

  get 'sync', to: 'sync#index'
  post 'sync', to: 'sync#verify'
  get 'refresh_sync', to: 'sync#refresh'
  delete 'sync', to: 'sync#desync'

  get 'matches', to: 'matches#index'
  get 'matches/:id', to: 'matches#show'
  post 'unmatch', to: 'matches#destroy'

  get 'my_profile', to: 'users#my_profile'
  get 'profile', to: 'users#edit_profile'
  post 'profile', to: 'users#update_profile'

  post 'like', to: 'likes#yes'
  post 'dislike', to: 'likes#no'

  get 'user_hub', to: 'home#user_hub'

  devise_for :users, controllers:
    { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'home#login'
  end

  get 'crawl', to: 'home#crawl'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:login, :crawl]

  def index
    unless current_user.gender
      # flash[:alert] = "You need to set a gender!"
      return redirect_to gender_path
    end

    unless current_user.lol_name
      flash[:alert] = "You need sync your LoL account!"
      return redirect_to sync_path
    end

    likings = current_user.liked_in + current_user.liker_in
    likings.each do |liking|
      liking.destroy if liking.created_at < Time.now - 5.days
    end

    dislikings = current_user.disliked_in + current_user.disliker_in
    dislikings.each do |disliking|
      disliking.destroy if disliking.created_at < Time.now - 5.days
    end

    all_users = User.where.not(id: current_user)

    # Filtering
    elos_to_show = current_user.elo_filters
    gender_pref = current_user.gender_pref

    filtered_users = all_users.select do |user|
      if user.gender != gender_pref && gender_pref != 'both'
        false
      elsif !elos_to_show.include? user.lol_tier
        false
      elsif user.region != current_user.region
        false
      else
        true
      end
    end
    # # #

    likeds = current_user.likeds
    dislikeds = current_user.dislikeds
    matches = current_user.matches
    known_users = likeds + dislikeds + matches

    free_users = (filtered_users - known_users).select { |user| user.lol_name }

    if free_users.size > 0
      users_who_like_me = free_users.select do |user|
        current_user.likers.include?(user)
      end

      if users_who_like_me.size > 0
        @candidate = users_who_like_me.sample
      else
        @candidate = free_users.sample
      end
    end
  end

  def login
    all_users = User.where.not(image: nil)
    girls = all_users.select { |user| user.gender == 'female' }.sample(3)
    boys = all_users.select { |user| user.gender == 'male' }

    @users = girls + boys.sample(5 - girls.length)
    # @users = User.where.not(image: nil).sample(5)
  end

  def user_hub
  end

  def crawl
    if params[:code] == 'Gfdg43gDFGg45d5gfJYG656y'
      sign_in User.find_by(email: '4y3t8743r@ry47.com')
    end
    redirect_to root_path
  end
end

# user.gender == gender_pref ||
# gender_pref == 'both' ||
# elos_to_show.include? user.lol_tier

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if @candidate %>

  <%= render partial: 'users/user', locals: {user: @candidate} %>

  <div class="flex-container" id="controls">

    <div class="like-btn">
      <%= form_with url: dislike_path, local: true do |f| %>
        <%= f.hidden_field :id, value: @candidate.id %>
        <%= f.submit :type => :image, :src => image_path("icons/dislike.png") %>
      <% end %>
    </div>

    <div class="like-btn">
      <%= form_with url: like_path, local: true do |f| %>
        <%= f.hidden_field :id, value: @candidate.id %>
        <%= f.submit :type => :image, :src => image_path("icons/like.png") %>
      <% end %>
    </div>
  </div>

<% else %>
  <div class="page-filler">
    <p>
      There is nobody else left right now, check back later!
    </p>
  </div>
<% end %>

app/views/home/login.html.erb
<p>
  <%= link_to user_facebook_omniauth_authorize_path, id: 'facebook-login' do %>
    <%= image_tag 'facebook.png' %>
    <span>Log in with Facebook</span>
  <% end %>
</p>

<div class="faded">
  <p class="small-text">
    or<br>
    <%= link_to "Sign up", new_user_registration_path %>
    /
    <%= link_to "Log in", new_user_session_path %>
    with e-mail
  </p>
</div>

<div id="CTA">
  <p>It's like Tinder for League of Legends</p>
  <div id="sample-box">
    <% @users.each do |user| %>
      <div class="user-sample">
        <%=
          image_tag user.photo,
          class: 'sample-photo'
        %>
        <%=
          image_tag user.badge,
          class: 'sample-badge' if user.lol_tier
        %>
      </div>
    <% end %>
  </div>
</div>

<p class="padding-1 text-justify">
  <small>
    DuoQ isn’t endorsed by Riot Games and doesn’t reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.
  </small>
</p>

app/views/home/user_hub.html.erb
<div id="hub-page">

  <div id="my-profile">
    <%= link_to my_profile_path do %>
      <%= image_tag(current_user.photo, class: 'hub-picture rounded') %>
    <% end %>
    <br>
    <%= link_to my_profile_path, id: 'my-name' do %>
      <h2 class="name"><%= current_user.name %></h2>
    <% end %>
  </div>

  <div class="flex-container">
    <div class="hub-box">
      <%= link_to settings_path do %>
        <%= image_tag 'icons/settings.png' %>
        <p>Settings</p>
      <% end %>
    </div>
    <div class="hub-box">
      <%= link_to profile_path do %>
        <%= image_tag 'icons/edit.png' %>
        <p>Edit Profile</p>
      <% end %>
    </div>
  </div>

</div>