config/routes.rb
Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'

  get 'settings', to: 'settings#index'
  patch 'settings', to: 'settings#update'
  get 'gender', to: 'settings#gender'
  patch 'gender', to: 'settings#set_gender'

  get 'sync', to: 'sync#index'
  post 'sync', to: 'sync#verify'
  get 'refresh_sync', to: 'sync#refresh'
  delete 'sync', to: 'sync#desync'

  get 'matches', to: 'matches#index'
  get 'matches/:id', to: 'matches#show'
  post 'unmatch', to: 'matches#destroy'

  get 'my_profile', to: 'users#my_profile'
  get 'profile', to: 'users#edit_profile'
  post 'profile', to: 'users#update_profile'

  post 'like', to: 'likes#yes'
  post 'dislike', to: 'likes#no'

  get 'user_hub', to: 'home#user_hub'

  devise_for :users, controllers:
    { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'home#login'
  end

  get 'crawl', to: 'home#crawl'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def gender
    redirect_to root_path if current_user.gender
  end

  def set_gender
    current_user.update!(settings_params)

    redirect_to root_path
  end

  def update
    current_user.update!(settings_params)

    redirect_to settings_path
  end

  private

  def settings_params
    allowed_params = [
      :gender_pref,
      :unranked_filter,
      :iron_filter,
      :bronze_filter,
      :silver_filter,
      :gold_filter,
      :platinum_filter,
      :diamond_filter,
      :master_filter,
      :grandmaster_filter,
      :challenger_filter
    ]
    allowed_params << :gender unless current_user.gender

    params.require(:user).permit(allowed_params)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/gender.html.erb
<div id="gender-page">

  <h2>I am:</h2>

  <div>
    <%= form_with model: current_user, url: gender_path, local: true do |f| %>
      <%= f.hidden_field :gender, value: 'male' %>
      <%= f.submit 'Male', class: 'btn' %>
    <% end %>
  </div>

  <div>
    <%= form_with model: current_user, url: gender_path, local: true do |f| %>
      <%= f.hidden_field :gender, value: 'female' %>
      <%= f.submit 'Female', class: 'btn' %>
    <% end %>
  </div>

</div>

app/views/settings/index.html.erb
<div id="settings-page">
  <%= form_with model: current_user, url: settings_path, local: true do |f| %>
    <% unless current_user.gender %>
      <h3>I am:</h3>
      <p>
        <%= f.label 'gender_male', 'Male' %>
        <%= f.radio_button :gender, 'male'%>
      </p>
      <p>
        <%= f.label 'gender_female', 'Female' %>
        <%= f.radio_button :gender, 'female'%>
      </p>

      <hr>
    <% end %>

    <h2>Sync Settings</h2>
    <div id="sync-settings">
      <p>
        <strong>LoL Name:</strong> <%= current_user.lol_name || 'None' %> <%= link_to '(Change)', sync_path %>
      </p>
      <p>
        <strong>Server:</strong> <%= current_user.region || 'None' %>
      </p>
      <p>
        <strong>Elo:</strong> <%= current_user.elo %> <%= link_to '(Refresh Elo)', refresh_sync_path %>
      </p>
    </div>

    <hr>

    <h2>Filter Settings</h2>
    <div id="filter-settings">

      <h3>Show me:</h3>
      <p>
        <%= f.radio_button :gender_pref, 'male'%>
        <%= f.label 'gender_pref_male', 'Male' %>
      </p>
      <p>
        <%= f.radio_button :gender_pref, 'female'%>
        <%= f.label 'gender_pref_female', 'Female' %>
      </p>
      <p>
        <%= f.radio_button :gender_pref, 'both'%>
        <%= f.label 'gender_pref_both', 'Both' %>
      </p>

      <h3>of Elo:</h3>
      <p>
        <%= f.check_box :unranked_filter %>
        <%= f.label 'unranked_filter', 'Unranked' %>
      </p>
      <p>
        <%= f.check_box :iron_filter %>
        <%= f.label 'iron_filter', 'Iron' %>
      </p>
      <p>
        <%= f.check_box :bronze_filter %>
        <%= f.label 'bronze_filter', 'Bronze' %>
      </p>
      <p>
        <%= f.check_box :silver_filter %>
        <%= f.label 'silver_filter', 'Silver' %>
      </p>
      <p>
        <%= f.check_box :gold_filter %>
        <%= f.label 'gold_filter', 'Gold' %>
      </p>
      <p>
        <%= f.check_box :platinum_filter %>
        <%= f.label 'platinum_filter', 'Platinum' %>
      </p>
      <p>
        <%= f.check_box :diamond_filter %>
        <%= f.label 'diamond_filter', 'Diamond' %>
      </p>
      <p>
        <%= f.check_box :master_filter %>
        <%= f.label 'master_filter', 'Master' %>
      </p>
      <p>
        <%= f.check_box :grandmaster_filter %>
        <%= f.label 'grandmaster_filter', 'Grandmaster' %>
      </p>
      <p>
        <%= f.check_box :challenger_filter %>
        <%= f.label 'challenger_filter', 'Challenger' %>
      </p>

      <%= f.submit 'Save', class: 'btn' %>

    </div>

  <% end %>

  <hr>

  <h2>Account Settings</h2>

  <p>
    Email: <%= current_user.email %>
  </p>
  <p>
    <%= link_to "Change email/password", edit_user_registration_path %>
  </p>
  <p>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  </p>

</div>