config/routes.rb
Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'

  get 'settings', to: 'settings#index'
  patch 'settings', to: 'settings#update'
  get 'gender', to: 'settings#gender'
  patch 'gender', to: 'settings#set_gender'

  get 'sync', to: 'sync#index'
  post 'sync', to: 'sync#verify'
  get 'refresh_sync', to: 'sync#refresh'
  delete 'sync', to: 'sync#desync'

  get 'matches', to: 'matches#index'
  get 'matches/:id', to: 'matches#show'
  post 'unmatch', to: 'matches#destroy'

  get 'my_profile', to: 'users#my_profile'
  get 'profile', to: 'users#edit_profile'
  post 'profile', to: 'users#update_profile'

  post 'like', to: 'likes#yes'
  post 'dislike', to: 'likes#no'

  get 'user_hub', to: 'home#user_hub'

  devise_for :users, controllers:
    { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'home#login'
  end

  get 'crawl', to: 'home#crawl'
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :firster, :class_name => "User", :foreign_key => "first_id"
  belongs_to :seconder, :class_name => "User", :foreign_key => "second_id"
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!

  def index
    current_user.new_matches = 0
    current_user.save

    @matches = current_user.matches
  end

  def show
    @match = User.find(params[:id])
    unless current_user.matches.include?(@match)
      redirect_to matches_path
    end
  end

  def destroy
    @match = User.find(params[:id])
    if current_user.matches.include?(@match)
      matches = current_user.first_in + current_user.second_in
      matches.each do |match|
        match.destroy if match.firster == @match || match.seconder == @match
      end
    end

    current_user.disliker_in.each do |disliking|
      disliking.destroy if disliking.disliked == @match
    end
    current_user.liker_in.each do |liking|
      liking.destroy if liking.liked == @match
    end

    Disliking.create(disliker: current_user, disliked: @match)

    redirect_to matches_path
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/index.html.erb
<div id="matches-page">
  <h2>Your DuoQ Matches</h2>

  <% unless @matches.size > 0 %>
    <div class="page-filler">
      <p>
        You don't have any matches yet.
      </p>
    </div>
  <% end %>

  <% @matches.each do |match| %>
    <%= link_to "matches/#{match.id}", class: 'match-link' do %>
      <div>
        <%= image_tag match.photo %>
      </div>
      <div>
        <p class="name">
          <strong>
            <%= match.name %>
          </strong>
        </p>
        <p>
          <em>
            <%= match.elo %>
          </em>
        </p>
        <p>
          <em>
            <%= match.region %>
          </em>
        </p>
        <% if match.lol_main %>
          <p>
            <em>
              <%= match.lol_main %> main
            </em>
          </p>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/matches/show.html.erb
<div id="match-page">
  <h2 class="name">
    <%= @match.name %>
  </h2>
  <%= render partial: 'users/user', locals: {user: @match} %>

  <div>
    <%= form_with url: unmatch_path, local: true do |f| %>
      <%= f.hidden_field :id, value: @match.id %>
      <%=
        f.submit 'Unmatch',
        class: 'btn',
        data: { confirm: 'Are you sure?' }
      %>
    <% end %>
  </div>
</div>