config/routes.rb
Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'

  get 'settings', to: 'settings#index'
  patch 'settings', to: 'settings#update'
  get 'gender', to: 'settings#gender'
  patch 'gender', to: 'settings#set_gender'

  get 'sync', to: 'sync#index'
  post 'sync', to: 'sync#verify'
  get 'refresh_sync', to: 'sync#refresh'
  delete 'sync', to: 'sync#desync'

  get 'matches', to: 'matches#index'
  get 'matches/:id', to: 'matches#show'
  post 'unmatch', to: 'matches#destroy'

  get 'my_profile', to: 'users#my_profile'
  get 'profile', to: 'users#edit_profile'
  post 'profile', to: 'users#update_profile'

  post 'like', to: 'likes#yes'
  post 'dislike', to: 'likes#no'

  get 'user_hub', to: 'home#user_hub'

  devise_for :users, controllers:
    { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'home#login'
  end

  get 'crawl', to: 'home#crawl'
end

app/views/layouts/_new_matches.html.erb
<span id="new-matches">
  <%= current_user.new_matches %>
</span>

app/views/layouts/_topbar.html.erb
<div id="topbar" data-url="<%= notifications_url %>">
  <% if current_page?(user_hub_path) ||
        current_page?(settings_path) ||
        current_page?(sync_path) ||
        current_page?(profile_path) %>
    <%= link_to user_hub_path, class: 'active' do %>
      <%= image_tag 'icons/userhub_active.png' %>
    <% end %>
  <% else %>
    <%= link_to user_hub_path do %>
      <%= image_tag 'icons/userhub.png' %>
    <% end %>
  <% end %>

  <% if current_page?(root_path) %>
    <%= link_to root_path, class: 'active' do %>
      <%= image_tag 'icons/main_active.png' %>
    <% end %>
  <% else %>
    <%= link_to root_path do %>
      <%= image_tag 'icons/main.png' %>
    <% end %>
  <% end %>

  <% if current_page?(matches_path) %>
    <%= link_to matches_path, class: 'active' do %>
      <%= image_tag 'icons/matches_active.png' %>
      <div id="new-matches-box">
        <% unless current_user.new_matches < 1 %>
          <%= render partial: 'layouts/new_matches' %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <%= link_to matches_path do %>
      <%= image_tag 'icons/matches.png' %>
      <div id="new-matches-box">
        <% unless current_user.new_matches < 1 %>
          <%= render partial: 'layouts/new_matches' %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <% if false %>
    <%= link_to "Profile", profile_path %> |
    <%= link_to "Sync", sync_path %> |
    <%= link_to "Settings", settings_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      DuoQ
      <% if user_signed_in? %>
        <% if current_user.new_matches > 0 %>
          (<%= current_user.new_matches %>)
        <% end %>
      <% end %>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="google-site-verification" content="jltp4fymjuWXmJHr3rk_9iXLEvLPyKz131w6r8U697U" />
    <%= favicon_link_tag asset_path('favicon.png') %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>
      <%= render partial: "layouts/topbar" %>
    <% else %>
      <%= link_to root_path, id: 'main-logo' do %>
        <h1>DuoQ<%= image_tag 'logo.png' %></h1>
      <% end %>
    <% end %>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
    
  </body>
</html>